config/routes.rb
Rails.application.routes.draw do
  
  
  # resources :categories
	root 'welcome#index'
  

  resources :blogs do
  	 resources :comnnts
  	end
  match 'auth/:provider/callback', to: 'sessionss#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessionss#destroy', as: 'signout', via: [:get, :post]
	# root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'welcome/index'
  # root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         has_many :categoryy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
mount_uploader :images, AvatarUploader
has_many :comnnts, dependent: :destroy
belongs_to :categoryy
  validates :title, presence: true,
                    length: { minimum: 5 }



 def self.search(search)
  where("title LIKE ?", "%#{search}%")
  end


end

app/models/categorie.rb
class Categorie < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/categoryy.rb
class Categoryy < ApplicationRecord
end

app/models/comnnt.rb
class Comnnt < ApplicationRecord
	belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :blogs
         
  end
         

app/models/user1.rb
class User1 < ActiveRecord::Base
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
       # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  # belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'   
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
	def index
	if 
     @blogs = Blog.search(params[:search])
	else
    @blogs = Blog.all
   end
	end

  
  


# def show
#     @blogs = Blog.find(params[:id])
#   end
 
    

  private

    def blog_params
      params.require(:blog).permit(:title, :description, :images, :dropdown)
    end
end

app/controllers/comnnts_controller.rb
class ComnntsController < InheritedResources::Base
  def create
    @blog = Blog.find(params[:blog_id])
    @comnnt = @blog.comnnts.create(comnnt_params)
    redirect_to blog_path(@blog)
  end
  private

    def comnnt_params
      params.require(:comnnt).permit(:title, :description)
    end
  #   def create
  #   @article = Article.find(params[:article_id])
  #   @comment = @article.comments.create(comment_params)
  #   redirect_to article_path(@article)
  # end
 
  # private
  #   def comment_params
  #     params.require(:comment).permit(:commenter, :body)
  #   end
end

# class CommentsController < ApplicationController
#   def create
#     @article = Article.find(params[:article_id])
#     @comment = @article.comments.create(comment_params)
#     redirect_to article_path(@article)
#   end
 
#   private
#     def comment_params
#       params.require(:comment).permit(:commenter, :body)
#     end
# end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
  if params[:q].nil?
    blog= []
  else
    @blog = Blog.search params[:q]
  end
end

end

app/controllers/sessionss_controller.rb
class SessionssController < ApplicationController
	def create

    user = User1.from_omniauth(env["omniauth.auth"])
    session[:user1_id] = user.id
    redirect_to new_blog_path
  end

  def destroy
    session[:user1_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
 
  if params[:search]
    @blog = Blog.search(params[:search])
  else
    @blog = Blog.all.order("created_at DESC")
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commentss_helper.rb
module CommentssHelper
end

app/helpers/comnnts_helper.rb
module ComnntsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :images %>
    <%= f.file_field :images %>
    
    
  </div>

  <div class="field">
  <%= f.label :dropdown %>
 <%= f.select(:categoryy, Categoryy.all.map{|cat| cat.title})%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% if current_user %>
      Welcome <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <% end %>
<p id="notice"><%= notice %></p>
<h1><%= link_to 'New Blog', new_blog_path %><h1>
 
<h1>Blog Search</h1>
<%= form_tag blogs_path(@blog), :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :title => nil %>
  </p>
<% end %>
<%= @blog %> 

    
  


 <!-- <table>
  <thead>
    <h1>BLOG</h1>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Images</th>
      <th>Dropdown</th>
        
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <!-- <tbody> --> 

    <% @blogs.each do |blog| %>
      <!-- <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= image_tag (blog.images) %></td> -->
        <!-- td><%= blog.dropdown %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
     <!--  </tr> -->
     <p>TITLE--- <%= blog.title %></p>
      <p>IMAGE-- <%= image_tag (blog.images) %></p>
     <p>Descroption-- <%= blog.description %></p>


      <h2>Add a comment:</h2>
      
    <%= form_for([blog, blog.comnnts.build]) do |f| %>
        <p>
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </p>
        <p>
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </p>
        <p>
          <%= f.submit %>
        </p>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
<% end %>
 
 
    <% end %>
    
  <!-- </tbody>
</table> -->

<%= link_to 'Back', blogs_path %>

app/views/blogs/new.html.erb
<% if current_user %>
      Welcome <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <% end %>
   
<h1>Create New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% if current_user %>
      Welcome <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  <strong>Images:</strong>
  <%= @blog.images %>
</p>

<p>
  <strong>Dropdown:</strong>
  <%= @blog.dropdown %>
</p>

<h2>Comments</h2>
<% @blog.comnnts.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.title %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.description %>
  </p>
 
 <%= link_to 'Destroy Comment', [comment.blog, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<% end %>
  
<h2>Add a comment:</h2>
<%= form_for([@blog, @blog.comnnts.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

 
 

<!-- < <h2>Add a comment</h2>
<h1>Comment</h1>
 <p>Title: <input type="text" name="title"></p>
 <p>Description: <input type="text" name="description"></p><br>
 <input type="submit" value="Submit"> -->

  
 <%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %> |
<td><%= link_to 'Destroy', @comnnt ,method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/comnnts/_form.html.erb
<%= form_for(comnnt) do |f| %>
  <% if comnnt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comnnt.errors.count, "error") %> prohibited this comnnt from being saved:</h2>

      <ul>
      <% comnnt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comnnts/edit.html.erb
<h1>Editing Comnnt</h1>

<%= render 'form', comnnt: @comnnt %>

<%= link_to 'Show', @comnnt %> |
<%= link_to 'Back', comnnts_path %>

app/views/comnnts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comnnts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comnnts.each do |comnnt| %>
      <tr>
        <td><%= comnnt.title %></td>
        <td><%= comnnt.description %></td>
        <td><%= link_to 'Show', comnnt %></td>
        <td><%= link_to 'Edit', edit_comnnt_path(comnnt) %></td>
        <td><%= link_to 'Destroy', comnnt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comnnt', new_comnnt_path %>

app/views/comnnts/new.html.erb
<h1>New Comnnt</h1>

<%= render 'form', comnnt: @comnnt %>

<%= link_to 'Back', comnnts_path %>

app/views/comnnts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comnnt.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comnnt.description %>
</p>

<%= link_to 'Edit', edit_comnnt_path(@comnnt) %> |
<%= link_to 'Back', comnnts_path %>