config/routes.rb
Rails.application.routes.draw do
  
  
  # resources :categories
	root 'welcome#index'
  

  resources :blogs do
  	 resources :comnnts
  	end
  match 'auth/:provider/callback', to: 'sessionss#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessionss#destroy', as: 'signout', via: [:get, :post]
	# root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'welcome/index'
  # root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         has_many :categoryy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
mount_uploader :images, AvatarUploader
has_many :comnnts, dependent: :destroy
belongs_to :categoryy
  validates :title, presence: true,
                    length: { minimum: 5 }



 def self.search(search)
  where("title LIKE ?", "%#{search}%")
  end


end

app/models/categorie.rb
class Categorie < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/categoryy.rb
class Categoryy < ApplicationRecord
end

app/models/comnnt.rb
class Comnnt < ApplicationRecord
	belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :blogs
         
  end
         

app/models/user1.rb
class User1 < ActiveRecord::Base
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
       # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  # belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'   
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
	def index
	if 
     @blogs = Blog.search(params[:search])
	else
    @blogs = Blog.all
   end
	end

  
  


# def show
#     @blogs = Blog.find(params[:id])
#   end
 
    

  private

    def blog_params
      params.require(:blog).permit(:title, :description, :images, :dropdown)
    end
end

app/controllers/comnnts_controller.rb
class ComnntsController < InheritedResources::Base
  def create
    @blog = Blog.find(params[:blog_id])
    @comnnt = @blog.comnnts.create(comnnt_params)
    redirect_to blog_path(@blog)
  end
  private

    def comnnt_params
      params.require(:comnnt).permit(:title, :description)
    end
  #   def create
  #   @article = Article.find(params[:article_id])
  #   @comment = @article.comments.create(comment_params)
  #   redirect_to article_path(@article)
  # end
 
  # private
  #   def comment_params
  #     params.require(:comment).permit(:commenter, :body)
  #   end
end

# class CommentsController < ApplicationController
#   def create
#     @article = Article.find(params[:article_id])
#     @comment = @article.comments.create(comment_params)
#     redirect_to article_path(@article)
#   end
 
#   private
#     def comment_params
#       params.require(:comment).permit(:commenter, :body)
#     end
# end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
  if params[:q].nil?
    blog= []
  else
    @blog = Blog.search params[:q]
  end
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
 
  if params[:search]
    @blog = Blog.search(params[:search])
  else
    @blog = Blog.all.order("created_at DESC")
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commentss_helper.rb
module CommentssHelper
end

app/helpers/comnnts_helper.rb
module ComnntsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/search/search.html.erb
<h1>Blog Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @blogs.each do |blog| %>
    <li>
      <h3>
        <%= link_to blog.title, controller: "blogs", action: "show", id: blog._id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<!-- <h1><%= link_to 'New Blog', new_blog_path %><h1 -->
     <% if current_user %>
      Welcome <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
    <% end %>

    <% if current_user %>
     <h1><%= link_to 'Create New Blog', new_blog_path %><h1>
    <% else %>
    <% end %>
    <% if current_user %>
     <%= link_to 'show blog', blogs_path %>
    <% else %>
    <% end %>
     

   
   
  
</div>
<h1><Blogs></h1>
    <!-- <p>
      <h3>BlogSearch</h3> <%= text_field_tag :search, params[:search], :class => "textfield-search" %>
      <%= submit_tag "Search", :name => nil, :class => "search-button" %>
    </p>
 -->
 
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/3/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.w3-row-padding img {margin-bottom: 12px}
/* Set the width of the sidebar to 120px */
.w3-sidebar {width: 120px;background: #222;}
/* Add a left margin to the "page content" that matches the width of the sidebar (120px) */
#main {margin-left: 120px}
/* Remove margins from "page content" on small screens */
@media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
<body class="w3-black">
  <!-- <h1><%= link_to 'Create New Blog', new_blog_path %><h1> -->
<!-- Icon Bar (Sidebar - hidden on small screens) -->


<!-- Navbar on small screens (Hidden on medium and large screens) -->


<!-- Page Content -->
<div class="w3-padding-large" id="main">
  <!-- Header/Home -->
  <header class="w3-container w3-padding-32 w3-center w3-black" id="home">
    <!-- <img src="https://www.theblogstarter.com/wp-content/uploads/2016/01/start-your-blog-4-steps.png" style="width:50%"> -->

   <!--  <img src= "http://simpleeconomist.com/wp-content/uploads/2014/08/blog.jpg" style="width:50%"> -->
    <img src ="http://www.higher-education-marketing.com/uploads/Blogging.jpg" style="width:50%">
  </header>

  <!-- About Section -->
  
    
    
    <!-- Grid for pricing tables -->
    

      
    
    <!-- Testimonials -->
    
  
  <!-- Portfolio Section -->
  
  <!-- End Portfolio Section -->
  

    
  <!-- End Contact Section -->
  </div>
  
    <!-- Footer -->
  

</body>
</html>