config/routes.rb
Rails.application.routes.draw do
  
  
  # resources :categories
	root 'welcome#index'
  

  resources :blogs do
  	 resources :comnnts
  	end
  match 'auth/:provider/callback', to: 'sessionss#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessionss#destroy', as: 'signout', via: [:get, :post]
	# root 'welcome#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'welcome/index'
  # root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
         has_many :categoryy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
mount_uploader :images, AvatarUploader
has_many :comnnts, dependent: :destroy
belongs_to :categoryy
  validates :title, presence: true,
                    length: { minimum: 5 }



 def self.search(search)
  where("title LIKE ?", "%#{search}%")
  end


end

app/models/categorie.rb
class Categorie < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/categoryy.rb
class Categoryy < ApplicationRecord
end

app/models/comnnt.rb
class Comnnt < ApplicationRecord
	belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :blogs
         
  end
         

app/models/user1.rb
class User1 < ActiveRecord::Base
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
       # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  # belongs_to :user, :class_name => 'User', :foreign_key => 'user_id'   
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
	def index
	if 
     @blogs = Blog.search(params[:search])
	else
    @blogs = Blog.all
   end
	end

  
  


# def show
#     @blogs = Blog.find(params[:id])
#   end
 
    

  private

    def blog_params
      params.require(:blog).permit(:title, :description, :images, :dropdown)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
  if params[:q].nil?
    blog= []
  else
    @blog = Blog.search params[:q]
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commentss_helper.rb
module CommentssHelper
end

app/helpers/comnnts_helper.rb
module ComnntsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!DOCTYPE html>


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: #00FFCC;">
  <div class="container">
    <div class="navbar-header">
       <a class="navbar-brand">BlogApp</a> 
      <!-- <h1><%= link_to 'Create New Blog', new_blog_path %><h1> -->

    </div>
    <ul class="nav navbar-nav">
      

       
      <!-- <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li> --> 
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <!-- <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul> -->
 <!--    <% if current_user %>
      Welcome <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      
    <% end %>
    -->
    
    
  
   <!--  <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
  </div>
</nav>



</body>
</html>

<html>
  <head>
    <title>Devise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     
  <% if current_user1 %>
    Welcome <strong><%= current_user1.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    
  <% end %>

    <%= yield %>
  </body>
</html>